name: Simulate Incident

on:
  workflow_dispatch:
    inputs:
      error_type:
        description: 'Type of error to simulate'
        required: true
        default: "http500"
        type: choice
        options:
          - http500
          - cpu
          - memory
          - crash

jobs:
  simulate_incident:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No Dependencies to install"

      - name: Run Incident Script
        run: python scripts/incident_simulation.py ${{ github.event.inputs.error_type }}
        
      - name: Send SNS Alert via AWS
        if: always()
        run: |
            aws sns publish \
            --topic-arn  ${{ secrets.SNS_TOPIC_ARN}} \
            --message "Incident simulation triggered: ${{ github.event.inputs.error_type }}"
        env:
            AWS_ACCESS_KEY_ID: ${{ SECRETS.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ SECRETS.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}



       